copy /Y .\IWB\resource.h .\CHS_RES\resource.h
copy /Y .\IWB\resource.h .\CHT_RES\resource.h
copy /Y .\IWB\resource.h .\DEU_RES\resource.h
copy /Y .\IWB\resource.h .\ESP_RES\resource.h
copy /Y .\IWB\resource.h .\FRA_RES\resource.h
copy /Y .\IWB\resource.h .\ITA_RES\resource.h
copy /Y .\IWB\resource.h .\KOR_RES\resource.h
copy /Y .\IWB\resource.h .\PTG_RES\resource.h
copy /Y .\IWB\resource.h .\RUS_RES\resource.h
copy /Y .\IWB\resource.h .\THAI_RES\resource.h
copy /Y .\IWB\resource.h .\VIT_RES\resource.h